# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a716377e1923efaf9e4d7863e888a582eb569f51d1abd2079d079c4517e1aa634ba3269f75be5974b2fe53107ce475dc57d51184dbb5ce0202b3c6cedf4a327b

test:
  secret_key_base: 3d78f2c8527615cdc445bfd3ec2e45fc2138182a9d7f0e553cee91ffa0421508f51feb53d2f9c81772c4165a411a060d75b6b28563ecd9af20b6bf03958edeea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
